---
title: "gs_power_ahr: computes power using average hazard ratio under non-proportional hazards"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true
    highlight: "textmate"
    css: "custom.css"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{gs_power_ahr: computes power using average hazard ratio under non-proportional hazards}
---

```{r, message=FALSE}
library(tibble)
library(dplyr)
#library(gsDesign2)
devtools::load_all()
```

# Introduction of `gs_power_ahr()`


# Use cases of `gs_power_ahr()`

## Example 1

```{r}
x <- gs_power_ahr(enrollRates = tibble(Stratum = "All", duration = c(2, 2, 10), rate = c(3, 6, 9)),
                  failRates = tibble(Stratum = "All", duration = c(3, 100), failRate = log(2) / c(9, 18), 
                                     hr = c(.9, .6), dropoutRate = rep(.001, 2)),
                  analysisTimes = c(12, 24, 36), events = NULL,
                  binding = TRUE,
                  upper = gs_spending_bound,
                  upar = list(sf = gsDesign::sfLDOF, total_spend = 0.025, param = NULL, timing = NULL),
                  lower = gs_spending_bound,
                  lpar = list(sf = gsDesign::sfLDOF, total_spend = 0.025, param = NULL, timing = NULL))
x
```



# Inner Logic of `gs_power_ahr()`

TODO