test_that("Snapshot test for creation of .rtf file under the fixed power design", {
  # Generate a summary
  x <- fixed_design_ahr(
    alpha = calculate_alpha(), power = 1 - calculate_beta(),
    enroll_rate = enroll_rate(),
    fail_rate = fail_rate(),
    study_duration = calculate_study_duration(),
    ratio = calculate_ratio()
  ) |> summary()

  # Create the .rtf file
  path <- tempfile(fileext = ".rtf")
  x |> as_rtf(file = path)

  local_edition(3)
  # Expect the existence of the custom file
  expect_snapshot_file(path, "custom_file.rtf")
})

test_that("Snapshot test for creation of fixed_design_ahr rtf file with custom title", {
  path <- tempfile(fileext = ".rtf")
  x <- fixed_design_ahr(
    alpha = calculate_alpha(), power = 1 - calculate_beta(),
    enroll_rate = enroll_rate(),
    fail_rate = fail_rate(),
    study_duration = calculate_study_duration(),
    ratio = calculate_ratio()
  ) |> summary() |> as_rtf(
    title = "Fixed design under non-proportional hazards",
    file = path
  )
  local_edition(3)
  expect_snapshot_file(path, "custom_title.rtf")
})

test_that("Snapshot test for creation of .rtf file with custom footnote", {
  x <- fixed_design_ahr(
    alpha = calculate_alpha(), power = 1 - calculate_beta(),
    enroll_rate = enroll_rate(),
    fail_rate = fail_rate(),
    study_duration = calculate_study_duration(),
    ratio = calculate_ratio()
  ) |> summary()
  path <- tempfile(fileext = ".rtf")
  x |> as_rtf(
    footnote = "Power computed with average hazard ratio method given the sample size",
    file = path
  )
  local_edition(3)
  expect_snapshot_file(path, "custom_footnote.rtf")
})

test_that("Snapshot test for creation of .rtf file under the Group sequential design using average hazard ratio", {
  path <- tempfile(fileext = ".rtf")
  gs_design_ahr() |> summary() |> as_rtf(file = path)
  local_edition(3)
  expect_snapshot_file(path, "gs_design_ahr.rtf")
})

test_that("Snapshot test for creation of .rtf file under the Group sequential design using weighted log-rank test", {
  path <- tempfile(fileext = ".rtf")
  gs_design_wlr() |> summary() |> as_rtf(file = path)
  local_edition(3)
  expect_snapshot_file(path, "gs_design_wlr.rtf")
})

test_that("Snapshot test for creation of .rtf file under the Group sequential design power using weighted log rank test", {
  path <- tempfile(fileext = ".rtf")
  gs_power_wlr() |> summary() |> as_rtf(file = path)
  local_edition(3)
  expect_snapshot_file(path, "gs_power_wlr.rtf")
})

test_that("Snapshot test for creation of .rtf file under the Group sequential design of binary outcome measuring in risk difference", {
  path <- tempfile(fileext = ".rtf")
  gs_design_rd() |> summary() |> as_rtf(file = path)
  local_edition(3)
  expect_snapshot_file(path, "gs_design_rd.rtf")
})

test_that("Snapshot test for creation of .rtf file with custom titles and subtitle and under the GS design power using weighted log rank test", {
  path <- tempfile(fileext = ".rtf")
  gs_power_wlr() |> summary() |> as_rtf(
    title = "Bound Summary",
    subtitle = "from gs_power_wlr",
    file = path
  )
  local_edition(3)
  expect_snapshot_file(path, "gs_power_wlr_custom_title.rtf")
})

test_that("Snapshot test for creation of .rtf file with custom spanner and sub-spanner under the GS design power using weighted log rank test", {
  path <- tempfile(fileext = ".rtf")
  gs_power_wlr() |> summary() |> as_rtf(
    colname_spanner = "Cumulative probability to cross boundaries",
    colname_spannersub = c("under H1", "under H0"),
    file = path
  )
  local_edition(3)
  expect_snapshot_file(path, "gs_power_wlr_custom_spanner.rtf")
})

test_that("Snapshot test for creation of .rtf file with custom footnote under the GS design power using weighted log rank test", {
  path <- tempfile(fileext = ".rtf")
  gs_power_wlr() |> summary() |> as_rtf(
    footnote = list(
      content = c(
        "approximate weighted hazard ratio to cross bound.",
        "wAHR is the weighted AHR.",
        "the crossing probability.",
        "this table is generated by gs_power_wlr."
      ),
      location = c("~wHR at bound", NA, NA, NA),
      attr = c("colname", "analysis", "spanner", "title")
    ),
    file = path
  )
  local_edition(3)
  expect_snapshot_file(path, "gs_power_wlr_custom_footnote.rtf")
})

test_that("Snapshot test for creation of .rtf file with columns to display in the summary table under the GS design power using weighted log rank test", {
  path <- tempfile(fileext = ".rtf")
  gs_power_wlr() |> summary() |> as_rtf(
    display_columns = c("Analysis", "Bound", "Nominal p", "Z", "Probability"),
    file = path
  )
  local_edition(3)
  expect_snapshot_file(path, "gs_power_wlr_cols_display.rtf")
})

test_that("Snapshot test for creation of .rtf file with efficacy bounds displayed in the summary table under the GS design power using weighted log rank test", {
  path <- tempfile(fileext = ".rtf")
  gs_power_wlr() |> summary() |> as_rtf(
    display_bound = "Efficacy",
    file = path
  )
  local_edition(3)
  expect_snapshot_file(path, "gs_power_wlr_eff_bound.rtf")
})

test_that("Snapshot test for creation of .rtf file with futility bounds displayed in the summary table under the GS design power using weighted log rank test", {
  path <- tempfile(fileext = ".rtf")
  gs_power_wlr(binding=TRUE) |> summary() |> as_rtf(
    display_bound = "Futility",
    file = path
  )
  local_edition(3)
  expect_snapshot_file(path, "gs_power_wlr_fut_bound.rtf")
})



