test_that("The observed_data and event_tbl gives the same output", {
  # Design parameters
  alpha <- 0.025
  beta <- 0.1
  ratio <- 1
  analysis_time <- c(20, 36)
  enroll_rate <- define_enroll_rate(duration = c(2, 2, 10), rate = (1:3) / 3)
  fail_rate <- define_fail_rate(duration = c(3, Inf), fail_rate = log(2) / 9,
                                hr = c(1, 0.6), dropout_rate = .0001)
  upper <- gs_spending_bound
  upar <- list(sf = sfLDOF, total_spend = alpha)

  # Original design
  x <- gs_design_ahr(
    enroll_rate = enroll_rate, fail_rate = fail_rate,
    alpha = alpha, beta = beta, ratio = ratio,
    info_scale = "h0_info",
    info_frac = NULL,
    analysis_time = c(20, 36),
    upper = gs_spending_bound, upar = upar,
    lower = gs_b, lpar = rep(-Inf, 2),
    test_upper = TRUE, test_lower = FALSE) |> to_integer()

  planned_event_ia <- x$analysis$event[1]
  planned_event_fa <- x$analysis$event[2]

  # Observed TTE data is assumed to be generated by simtrial
  set.seed(123)
  observed_data <- simtrial::sim_pw_surv(
    n = x$analysis$n[x$analysis$analysis == 2],
    stratum = data.frame(stratum = "All", p = 1),
    block = c(rep("control", 2), rep("experimental", 2)),
    enroll_rate = x$enroll_rate,
    fail_rate = (fail_rate |> simtrial::to_sim_pw_surv())$fail_rate,
    dropout_rate = (fail_rate |> simtrial::to_sim_pw_surv())$dropout_rate)

  observed_data_ia <- observed_data |> simtrial::cut_data_by_date(x$analysis$time[1])
  observed_data_fa <- observed_data |> simtrial::cut_data_by_date(x$analysis$time[2])

  observed_event_ia <- sum(observed_data_ia$event)
  observed_event_fa <- sum(observed_data_fa$event)

  # Approach 1: Updated design by input the blinded TTE data
  ustime <- c(observed_event_ia / planned_event_fa, 1)
  y1 <- gs_update_ahr(x = x,
                      ustime = ustime,
                      observed_data = list(observed_data_ia, observed_data_fa))

  # Approach 2: Updated design by input event table per analysis per piecewise interval
  pw_event_ia <- simtrial::fit_pwexp(srv = survival::Surv(time = observed_data_ia$tte,
                                                           event = observed_data_ia$event),
                                      intervals = fail_rate$duration)[, 3]
  pw_event_fa <- simtrial::fit_pwexp(srv = survival:: Surv(time = observed_data_fa$tte,
                                                            event = observed_data_fa$event),
                                      intervals = fail_rate$duration)[, 3]

  y2 <- gs_update_ahr(x = x,
                      ustime = ustime,
                      event_tbl = data.frame(analysis = c(1, 1, 2, 2),
                                             event_tbl = c(pw_event_ia, pw_event_fa)))

  expect_equal(y1, y2)
})
