
test_that("as_gt.fixed_design creates a valid gt table", {
  enroll_rate <- define_enroll_rate(duration = 18, rate = 20)
  fail_rate <- define_fail_rate(duration = c(4, 100), fail_rate = log(2) / 12, dropout_rate = .001, hr = c(1, .6))
  study_duration <- 36
  ratio <- 1
  alpha <- 0.025
  beta <- 0.1

  ahr_result <- fixed_design_ahr(alpha = alpha, power = 1 - beta, enroll_rate = enroll_rate, fail_rate = fail_rate, study_duration = study_duration, ratio = ratio)
  ahr_table <- ahr_result %>% summary() %>% as_gt.fixed_design()

  expect_s3_class(ahr_table, "gt_tbl")

})






test_that("as_gt.fixed_design handles custom title and footnote", {
  enroll_rate <- define_enroll_rate(duration = 18, rate = 20)
  fail_rate <- define_fail_rate(duration = c(4, 100), fail_rate = log(2) / 12, dropout_rate = .001, hr = c(1, .6))
  study_duration <- 36
  ratio <- 1
  alpha <- 0.025
  beta <- 0.1

  ahr_result <- fixed_design_ahr(alpha = alpha, power = 1 - beta, enroll_rate = enroll_rate, fail_rate = fail_rate, study_duration = study_duration, ratio = ratio)
  ahr_table <- ahr_result %>% summary() %>% as_gt.fixed_design(title = "Custom Title", footnote = list(content = "Custom Footnote"))

  expect_s3_class(ahr_table, "gt_tbl")

})



# Define the test
test_that("enroll_rate function produces the expected output", {
  # Set up the expected result
  expected_result <- tibble::tibble(
    stratum = "All",
    duration = 18,
    rate = 20
  )

  # Call the function
  result <- define_enroll_rate(duration = 18, rate = 20)

  # Check if the actual result matches the expected result
  expect_identical(as.data.frame(result), as.data.frame(expected_result))
})

# Define the test
test_that("fail_rate function produces the expected output", {
  # Set up the expected result
  expected_result <- tibble::tibble(
    stratum = "All",
    duration = c(4, 100),
    fail_rate = 0.0578,
    dropout_rate = 0.001,
    hr = c(1, 0.6)
  )

  # Call the function
  result <- define_fail_rate(
    duration = c(4, 100),
    fail_rate = log(2) / 12,
    dropout_rate = 0.001,
    hr = c(1, 0.6)
  )

  expect_equal(result$stratum, expected_result$stratum)
  expect_equal(result$duration, expected_result$duration)
  expect_true(all(abs(result$fail_rate - expected_result$fail_rate) < 1e-4)) # Check if the fail_rate values are within a tolerance
  expect_equal(result$dropout_rate, expected_result$dropout_rate)
  expect_equal(result$hr, expected_result$hr)
})
test_that("Snapshot test for gs_power_wlr summary as_gt", {

  output <-  gs_power_wlr() %>%
    summary() %>%
    as_gt(
      footnote = list(
        content = c(
          "approximate weighted hazard ratio to cross bound.",
          "wAHR is the weighted AHR.",
          "the crossing probability.",
          "this table is generated by gs_power_wlr."
           ),
      location = c("~wHR at bound", NA, NA, NA),
        attr = c("colname", "analysis", "spanner", "title")
         )
      )


  # Compare the actual output with the expected snapshot
  expect_snapshot("~/gsDesign2/gsdesign2/tests/testthat/_snaps/WLR_design.PNG")
})

test_that("Snapshot test for gs_design_ahr summary gt table", {

  output <-  gs_design_ahr() %>%
    summary() %>%
    as_gt()

  # Compare the actual output with the expected snapshot
  expect_snapshot("~/gsDesign2/gsdesign2/tests/testthat/_snaps/AHR_design.PNG")
})

test_that("Snapshot test for gs_power_combo summary gt table", {

  output <-  gs_power_combo() %>%
    summary() %>%
    as_gt()
  # Compare the actual output with the expected snapshot
  expect_snapshot("~/gsDesign2/gsdesign2/tests/testthat/_snaps/MaxCombo_design.PNG")
})

test_that("Snapshot test for gs_design_rd summary gt table", {

  output <-  gs_power_combo() %>%
    summary() %>%
    as_gt()
  # Compare the actual output with the expected snapshot
  expect_snapshot("~/gsDesign2/gsdesign2/tests/testthat/_snaps/binary_endpoint.PNG")
})

test_that("Snapshot test for gs_power_wlr summary gt table with colname_spanner and colname_spannersub parameters", {

  output <-  gs_power_wlr() %>%
        summary() %>%
       as_gt(
          colname_spanner = "Cumulative probability to cross boundaries",
          colname_spannersub = c("under H1", "under H0")
      )
  # Compare the actual output with the expected snapshot
  expect_snapshot("~/gsDesign2/gsdesign2/tests/testthat/_snaps/wlr_design_w_col_spanner.PNG")
})

test_that("Snapshot test for gs_power_wlr summary gt table with custom title and subtitle", {

  output <-gs_power_wlr() %>%
    summary() %>%
    as_gt(
       title = "Bound Summary",
        subtitle = "from gs_power_wlr"
      )
  # Compare the actual output with the expected snapshot
  expect_snapshot("~/gsDesign2/gsdesign2/tests/testthat/_snaps/wlr_design_w_title.PNG")
})

test_that("Snapshot test for gs_power_wlr summary gt table with custom footnotes", {

  output <- gs_power_wlr() %>%
      summary() %>%
      as_gt(
       footnote = list(
         content = c(
           "approximate weighted hazard ratio to cross bound.",
          "wAHR is the weighted AHR.",
          "the crossing probability.",
          "this table is generated by gs_power_wlr."
           ),
         location = c("~wHR at bound", NA, NA, NA),
         attr = c("colname", "analysis", "spanner", "title")
        )
      )
  # Compare the actual output with the expected snapshot
  expect_snapshot("~/gsDesign2/gsdesign2/tests/testthat/_snaps/wlr_design_w_footnote.PNG")
})

test_that("Snapshot test for gs_power_wlr summary gt table with Efficacy bound row", {

  output <-  gs_power_wlr() %>%
             summary() %>%
             as_gt(display_bound = "Efficacy")
  # Compare the actual output with the expected snapshot
  expect_snapshot("~/gsDesign2/gsdesign2/tests/testthat/_snaps/wlr_design_w_efficacybound.PNG")
})


test_that("Snapshot test for fixed_design under Fleming-Harrington method gt table", {

  enroll_rate <- define_enroll_rate(
    duration = 18,
    rate = 20
    )
  fail_rate <- define_fail_rate(
    duration = c(4, 100),
    fail_rate = log(2) / 12,
    dropout_rate = .001,
    hr = c(1, .6)
    )

  #default parameters for the ratio, alpha, beta and study duration

  ratio <- 1
  alpha <- 0.025
  beta <- 0.1
  study_duration <- 36

  fixed_design_fh(
    alpha = alpha, power = 1 - beta,
    enroll_rate = enroll_rate, fail_rate = fail_rate,
    study_duration = study_duration, ratio = ratio
    ) %>%
    summary() %>%
    as_gt()
  # Compare the actual output with the expected snapshot
  expect_snapshot("~/gsDesign2/gsdesign2/tests/testthat/_snaps/fixed_design-Fleming.PNG")
})