# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gridptsRcpp <- function(r, mu, a, b) {
    .Call(`_gsDesign2_gridptsRcpp`, r, mu, a, b)
}

.h1Rcpp <- function(r, theta, I, a, b) {
    .Call(`_gsDesign2_h1Rcpp`, r, theta, I, a, b)
}

.hupdateRcpp <- function(r, theta, I, a, b, thetam1, Im1, gm1) {
    .Call(`_gsDesign2_hupdateRcpp`, r, theta, I, a, b, thetam1, Im1, gm1)
}

