# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gridpts_rcpp <- function(r, mu, a, b) {
    .Call(`_gsDesign2_gridpts_rcpp`, r, mu, a, b)
}

h1_rcpp <- function(r, theta, I, a, b) {
    .Call(`_gsDesign2_h1_rcpp`, r, theta, I, a, b)
}

hupdate_rcpp <- function(r, theta, I, a, b, thetam1, Im1, gm1) {
    .Call(`_gsDesign2_hupdate_rcpp`, r, theta, I, a, b, thetam1, Im1, gm1)
}

